import { MigrationInterface, QueryRunner } from "typeorm";

export class InsertBooksIntoBook1612544293850 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            INSERT INTO book (title, author) VALUES
            ('To Kill a Mockingbird', 'Harper Lee'),
            ('1984', 'George Orwell'),
            ('The Great Gatsby', 'F. Scott Fitzgerald'),
            ('Pride and Prejudice', 'Jane Austen'),
            ('The Catcher in the Rye', 'J.D. Salinger'),
            ('The Hobbit', 'J.R.R. Tolkien'),
            ('Fahrenheit 451', 'Ray Bradbury'),
            ('Jane Eyre', 'Charlotte Bronte'),
            ('Animal Farm', 'George Orwell'),
            ('Wuthering Heights', 'Emily Bronte'),
            ('Lord of the Flies', 'William Golding'),
            ('Moby Dick', 'Herman Melville'),
            ('War and Peace', 'Leo Tolstoy'),
            ('The Odyssey', 'Homer'),
            ('Ulysses', 'James Joyce'),
            ('Madame Bovary', 'Gustave Flaubert'),
            ('The Divine Comedy', 'Dante Alighieri'),
            ('The Brothers Karamazov', 'Fyodor Dostoevsky'),
            ('Don Quixote', 'Miguel de Cervantes'),
            ('Crime and Punishment', 'Fyodor Dostoevsky'),
            ('Anna Karenina', 'Leo Tolstoy'),
            ('One Hundred Years of Solitude', 'Gabriel García Márquez'),
            ('Catch-22', 'Joseph Heller'),
            ('The Picture of Dorian Gray', 'Oscar Wilde'),
            ('Brave New World', 'Aldous Huxley'),
            ('A Clockwork Orange', 'Anthony Burgess'),
            ('The Sound and the Fury', 'William Faulkner'),
            ('Gone with the Wind', 'Margaret Mitchell'),
            ('The Bell Jar', 'Sylvia Plath'),
            ('Infinite Jest', 'David Foster Wallace'),
            ('The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams'),
            ('Slaughterhouse-Five', 'Kurt Vonnegut'),
            ('Les Misérables', 'Victor Hugo'),
            ('Walden', 'Henry David Thoreau'),
            ('Pippi Longstocking', 'Astrid Lindgren'),
            ('The Three Musketeers', 'Alexandre Dumas'),
            ('Anne of Green Gables', 'Lucy Maud Montgomery'),
            ('Frankenstein', 'Mary Shelley'),
            ('Dracula', 'Bram Stoker'),
            ('Alice''s Adventures in Wonderland', 'Lewis Carroll'),
            ('The Adventures of Sherlock Holmes', 'Arthur Conan Doyle'),
            ('The War of the Worlds', 'H.G. Wells'),
            ('Around the World in Eighty Days', 'Jules Verne'),
            ('A Tale of Two Cities', 'Charles Dickens'),
            ('Great Expectations', 'Charles Dickens'),
            ('Oliver Twist', 'Charles Dickens'),
            ('The Scarlet Letter', 'Nathaniel Hawthorne'),
            ('The Adventures of Huckleberry Finn', 'Mark Twain'),
            ('The Call of the Wild', 'Jack London'),
            ('White Fang', 'Jack London'),
            ('Treasure Island', 'Robert Louis Stevenson'),
            ('Robinson Crusoe', 'Daniel Defoe'),
            ('Gulliver''s Travels', 'Jonathan Swift'),
            ('Pride and Prejudice and Zombies', 'Seth Grahame-Smith'),
            ('The Hound of the Baskervilles', 'Arthur Conan Doyle'),
            ('Heart of Darkness', 'Joseph Conrad'),
            ('The Strange Case of Dr Jekyll and Mr Hyde', 'Robert Louis Stevenson'),
            ('The Wind in the Willows', 'Kenneth Grahame'),
            ('A Christmas Carol', 'Charles Dickens'),
            ('The Jungle Book', 'Rudyard Kipling'),
            ('The Adventures of Tom Sawyer', 'Mark Twain'),
            ('Little Women', 'Louisa May Alcott'),
            ('Beloved', 'Toni Morrison'),
            ('The Stand', 'Stephen King'),
            ('The Alchemist', 'Paulo Coelho'),
            ('The Road', 'Cormac McCarthy'),
            ('The Shining', 'Stephen King'),
            ('The Handmaid''s Tale', 'Margaret Atwood'),
            ('Life of Pi', 'Yann Martel'),
            ('The Hunger Games', 'Suzanne Collins'),
            ('Jurassic Park', 'Michael Crichton'),
            ('The Girl with the Dragon Tattoo', 'Stieg Larsson'),
            ('The Da Vinci Code', 'Dan Brown'),
            ('The Secret Garden', 'Frances Hodgson Burnett'),
            ('The Chronicles of Narnia', 'C.S. Lewis'),
            ('Charlotte''s Web', 'E.B. White'),
            ('The Outsiders', 'S.E. Hinton'),
            ('The Perks of Being a Wallflower', 'Stephen Chbosky'),
            ('The Lovely Bones', 'Alice Sebold'),
            ('The Help', 'Kathryn Stockett'),
            ('The Book Thief', 'Markus Zusak'),
            ('The Fault in Our Stars', 'John Green'),
            ('The Giver', 'Lois Lowry'),
            ('The Harry Potter series', 'J.K. Rowling');
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP TABLE book;
        `);
    }
}
